language: generic

sudo : required

services : 
  - docker 

before_install :
  - docker build -t multi-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true multi-docker npm run test -- --coverage